package com.hdlee.pdfnote;
import android.app.Activity;
import android.graphics.*;
import android.net.Uri;
import android.view.MotionEvent;
import android.widget.FrameLayout;
import org.junit.*;
import org.junit.runner.RunWith;
import org.robolectric.*;
import org.robolectric.annotation.*;
import java.io.*;
import java.lang.reflect.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import static org.junit.Assert.*;
@RunWith(RobolectricTestRunner.class)
@Config(sdk=28,qualifiers="mdpi",shadows=ReadingToolbarTest.RendererShadow.class)
@GraphicsMode(GraphicsMode.Mode.NATIVE)
public class NotebookFeatureTest {
    @Test public void pageElementsPersistAndSearchFindsTypedNotes()throws Exception{AnnotationStore store=new AnnotationStore(RuntimeEnvironment.getApplication());store.open(Uri.parse("content://notebook/"+UUID.randomUUID()));AnnotationStore.PageElement element=new AnnotationStore.PageElement();element.text="Financial research 금융";store.elements.add(element);store.save();AnnotationStore restored=new AnnotationStore(RuntimeEnvironment.getApplication());String backup=store.exportJson(Uri.parse("content://test"),"note");restored.importJson(backup,2);assertEquals(1,restored.elements.size());assertEquals(1,SearchScanner.annotations(restored,"financial").size());assertEquals(1,SearchScanner.annotations(restored,"금융").size());assertTrue(SearchScanner.annotations(restored,"missing").isEmpty());}
    @Test public void invalidGeometryDoesNotReplaceExistingNotes()throws Exception{AnnotationStore store=new AnnotationStore(RuntimeEnvironment.getApplication());AnnotationStore.PageElement element=new AnnotationStore.PageElement();element.text="keep";store.elements.add(element);org.json.JSONObject root=new org.json.JSONObject(store.exportJson(Uri.parse("content://test"),"note"));root.getJSONArray("elements").getJSONObject(0).put("right",2);try{store.importJson(root.toString(),1);fail();}catch(org.json.JSONException expected){}assertEquals("keep",store.elements.get(0).text);}
    @Test public void notebookNamesNeverEscapeFolderAndDuplicatesStayIntact()throws Exception{File folder=new File(RuntimeEnvironment.getApplication().getCacheDir(),UUID.randomUUID().toString());folder.mkdir();for(String name:new String[]{"../escape","a/b","..",""})try{NotebookFiles.unique(folder,name);fail();}catch(IOException expected){}File first=NotebookFiles.unique(folder,"Study.pdf");try(OutputStream out=new FileOutputStream(first)){out.write(new byte[]{1,2,3});}File second=NotebookFiles.unique(folder,"Study.pdf");assertNotEquals(first,second);assertEquals("Study (1).pdf",second.getName());assertEquals(3,first.length());}
    @Test public void readModeTurnsPagesFromBodyAndEdges()throws Exception{Activity activity=Robolectric.buildActivity(Activity.class).setup().get();final List<Integer> swipes=new ArrayList<>();PdfPageView.Listener listener=(PdfPageView.Listener)Proxy.newProxyInstance(PdfPageView.Listener.class.getClassLoader(),new Class<?>[]{PdfPageView.Listener.class},(proxy,method,args)->{if(method.getName().equals("onPageSwipe"))swipes.add((Integer)args[0]);return null;});PdfPageView view=new PdfPageView(activity,listener);FrameLayout parent=new FrameLayout(activity);parent.addView(view);activity.setContentView(parent);parent.layout(0,0,1000,1000);view.layout(0,0,1000,1000);view.showPage(Bitmap.createBitmap(1000,1000,Bitmap.Config.ARGB_8888),0,new ArrayList<>(),new ArrayList<>(),new ArrayList<>());view.setPageSwipeEnabled(true);drag(view,500,508);assertTrue(swipes.isEmpty());drag(view,500,900);assertEquals(Collections.singletonList(-1),swipes);drag(view,5,200);assertEquals(Arrays.asList(-1,-1),swipes);}
    private static void drag(PdfPageView view,float x,float end){long t=android.os.SystemClock.uptimeMillis();int[] actions={MotionEvent.ACTION_DOWN,MotionEvent.ACTION_MOVE,MotionEvent.ACTION_UP};for(int i=0;i<3;i++){MotionEvent event=MotionEvent.obtain(t,t+100*i,actions[i],i==0?x:end,100,0);view.onTouchEvent(event);event.recycle();}}
    @Test public void straightToolRetainsOnlyStartAndEnd()throws Exception{Activity activity=Robolectric.buildActivity(Activity.class).setup().get();PdfPageView.Listener listener=(PdfPageView.Listener)Proxy.newProxyInstance(PdfPageView.Listener.class.getClassLoader(),new Class<?>[]{PdfPageView.Listener.class},(p,m,a)->null);PdfPageView view=new PdfPageView(activity,listener);FrameLayout parent=new FrameLayout(activity);parent.addView(view);activity.setContentView(parent);parent.layout(0,0,1000,1000);view.layout(0,0,1000,1000);List<AnnotationStore.InkStroke> strokes=new ArrayList<>();view.showPage(Bitmap.createBitmap(1000,1000,Bitmap.Config.ARGB_8888),0,new ArrayList<>(),strokes,new ArrayList<>());view.setFingerInk(true);view.setInkTool(3,Color.BLUE,.005f);long time=1;int[] actions={0,2,2,1};float[] xs={100,200,350,500};for(int i=0;i<4;i++){MotionEvent e=MotionEvent.obtain(time,time+20*i,actions[i],xs[i],100+i*80,0);view.onTouchEvent(e);e.recycle();}assertEquals(1,strokes.size());assertEquals(2,strokes.get(0).points.size());assertEquals(.5f,strokes.get(0).points.get(1).x,.001);}
    @Test public void toolsMenuHasOneActionPerItem()throws Exception{MainActivity activity=Robolectric.buildActivity(MainActivity.class).setup().get();Method method=MainActivity.class.getDeclaredMethod("showTools");method.setAccessible(true);method.invoke(activity);android.app.Dialog menu=org.robolectric.shadows.ShadowDialog.getLatestDialog();assertTrue(hasText(menu.getWindow().getDecorView(),"문서"));assertFalse("문서 없이는 문서 관련 메뉴를 숨깁니다",hasText(menu.getWindow().getDecorView(),"보기·이동"));menu.dismiss();java.lang.reflect.Field renderer=MainActivity.class.getDeclaredField("renderer");renderer.setAccessible(true);renderer.set(activity,new android.graphics.pdf.PdfRenderer(null));method.invoke(activity);menu=org.robolectric.shadows.ShadowDialog.getLatestDialog();assertTrue(hasText(menu.getWindow().getDecorView(),"보기·이동"));assertTrue(hasText(menu.getWindow().getDecorView(),"타이핑"));assertTrue(hasText(menu.getWindow().getDecorView(),"필기·삽입"));assertTrue(hasText(menu.getWindow().getDecorView(),"학습·주석"));assertTrue(hasText(menu.getWindow().getDecorView(),"내보내기·백업"));menu.dismiss();Method add=MainActivity.class.getDeclaredMethod("showAddDocumentMenu");add.setAccessible(true);add.invoke(activity);android.app.Dialog choices=org.robolectric.shadows.ShadowDialog.getLatestDialog();android.view.View sheet=choices.getWindow().getDecorView();assertNotNull(sheet.findViewWithTag("action_sheet"));assertTrue(hasText(sheet,"파일 가져오기"));assertTrue(hasText(sheet,"저장된 문서 열기"));assertTrue(hasText(sheet,"새 노트 만들기"));assertTrue(hasText(sheet,"취소"));}
    private static boolean hasText(android.view.View view,String text){if(view instanceof android.widget.TextView&&text.contentEquals(((android.widget.TextView)view).getText()))return true;if(view instanceof android.view.ViewGroup){android.view.ViewGroup group=(android.view.ViewGroup)view;for(int i=0;i<group.getChildCount();i++)if(hasText(group.getChildAt(i),text))return true;}return false;}
}
