package com.hdlee.pdfnote;
import android.content.Context;
import android.graphics.*;
import java.io.File;

final class AnnotationPainter {
    private static final android.util.LruCache<String,Bitmap> images=new android.util.LruCache<String,Bitmap>(12*1024*1024){@Override protected int sizeOf(String key,Bitmap value){return value.getAllocationByteCount();}};
    private static Bitmap image(File file){Bitmap b=images.get(file.getPath());if(b==null){b=BitmapFactory.decodeFile(file.getPath());if(b!=null)images.put(file.getPath(),b);}return b;}
    static void text(Canvas canvas,String text,RectF box,float size,int color){Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);p.setColor(color);p.setTextSize(size);int save=canvas.save();canvas.clipRect(box);float y=box.top+size;for(String paragraph:text.split("\n",-1)){String remaining=paragraph;while(!remaining.isEmpty()){int n=Math.max(1,p.breakText(remaining,true,box.width(),null));canvas.drawText(remaining.substring(0,n),box.left,y,p);y+=size*1.35f;remaining=remaining.substring(n);}if(paragraph.isEmpty())y+=size*1.35f;}canvas.restoreToCount(save);}
    static RectF box(RectF dest,AnnotationStore.PageElement e){return new RectF(dest.left+e.left*dest.width(),dest.top+e.top*dest.height(),dest.left+e.right*dest.width(),dest.top+e.bottom*dest.height());}
    static void elements(Context context,Canvas c,RectF d,AnnotationStore store,int page){if(store==null)return;for(AnnotationStore.PageElement e:store.elements){if(e.page!=page)continue;RectF b=box(d,e);if(e.kind.equals("image")){File file=new File(new File(context.getFilesDir(),"images"),e.asset);Bitmap image=image(file);if(image!=null){RectF fitted=new RectF();new Matrix().setRectToRect(new RectF(0,0,image.getWidth(),image.getHeight()),b,Matrix.ScaleToFit.CENTER);float scale=Math.min(b.width()/image.getWidth(),b.height()/image.getHeight());fitted.set(b.centerX()-image.getWidth()*scale/2,b.centerY()-image.getHeight()*scale/2,b.centerX()+image.getWidth()*scale/2,b.centerY()+image.getHeight()*scale/2);c.drawBitmap(image,null,fitted,new Paint(Paint.ANTI_ALIAS_FLAG|Paint.FILTER_BITMAP_FLAG));}}else{text(c,(e.kind.equals("link")?"↗ ":"")+e.text,b,Math.max(9,d.width()*.027f),e.kind.equals("link")?0xFF2563EB:0xFF172033);}}}
    static void all(Context context,Canvas c,RectF d,AnnotationStore store,int page){Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);for(AnnotationStore.Mark m:store.marks)if(m.page==page){RectF b=new RectF(d.left+m.left*d.width(),d.top+m.top*d.height(),d.left+m.right*d.width(),d.top+m.bottom*d.height());if(!m.noteOnly){p.setColor(m.color);c.drawRect(b,p);}if(m.visible&&m.note!=null&&!m.note.isEmpty()){RectF note=new RectF(b.right,b.top,Math.min(d.right,b.right+d.width()*.35f),Math.min(d.bottom,b.top+d.height()*.12f));p.setColor(0xFFFFF7D6);c.drawRect(note,p);text(c,m.minimized?"메모":m.note,note,d.width()*.023f,0xFF172033);}}for(AnnotationStore.InkStroke s:store.strokes)if(s.page==page){p.setColor(s.color);p.setStrokeCap(Paint.Cap.ROUND);for(int i=0;i<s.points.size();i++){AnnotationStore.InkPoint b=s.points.get(i),a=s.points.get(Math.max(0,i-1));float width=Math.max(1.5f,s.width*d.width()*(.45f+(a.pressure+b.pressure)/2*1.15f));p.setStrokeWidth(width);if(i==0)c.drawCircle(d.left+b.x*d.width(),d.top+b.y*d.height(),width/2,p);else c.drawLine(d.left+a.x*d.width(),d.top+a.y*d.height(),d.left+b.x*d.width(),d.top+b.y*d.height(),p);}}for(AnnotationStore.TranslationNote n:store.translations)if(n.page==page&&n.visible){RectF box=new RectF(d.left+n.right*d.width(),d.top+n.top*d.height(),Math.min(d.right,d.left+n.right*d.width()+d.width()*.35f),Math.min(d.bottom,d.top+n.top*d.height()+d.height()*.12f));p.setColor(0xFFF3E8FF);c.drawRect(box,p);text(c,n.minimized?"번역":n.translated,box,d.width()*.023f,0xFF172033);}elements(context,c,d,store,page);}
}
