package com.hdlee.pdfnote;

import android.app.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.graphics.pdf.PdfRenderer;
import android.net.Uri;
import android.os.ParcelFileDescriptor;
import android.view.*;
import android.widget.*;
import android.text.*;
import java.io.File;
import java.util.*;
import java.util.concurrent.*;

/** Document shelf: folder tree, breadcrumbs and covers with a compact action menu. */
final class LibraryDialog extends Dialog {
    interface Actions {
        void open(File file);
        void importFiles(File folder);
        void newNote(File folder,Runnable refresh);
        void changed(File source,File target,boolean moved);
        void selectedFolder(File folder);
        default void removed(List<File> files){}
    }
    private final Activity activity;
    private final LibraryRepository repository;
    private final Actions actions;
    private File folder;
    private FolderTreeView tree;
    private LinearLayout content,body,grid,breadcrumb;
    private ScrollView shelf;
    private TextView heading,sortButton,viewButton,selectButton,selectionCount;
    private EditText search;private LinearLayout selectionBar;
    private final Set<File> selected=new LinkedHashSet<>();private boolean selectionMode;
    private static final android.util.LruCache<String,Bitmap> covers=new android.util.LruCache<String,Bitmap>(12*1024*1024){protected int sizeOf(String key,Bitmap image){return image.getAllocationByteCount();}};
    private final ExecutorService previews=Executors.newSingleThreadExecutor();
    private int generation;
    private boolean allMode;private TextView allButton,foldersButton;
    private boolean busy;
    LibraryDialog(Activity activity,LibraryRepository repository,File folder,Actions actions){
        super(activity);this.activity=activity;this.repository=repository;this.folder=folder;this.actions=actions;requestWindowFeature(Window.FEATURE_NO_TITLE);
        content=new LinearLayout(activity);content.setTag("library_root");content.setOrientation(LinearLayout.VERTICAL);content.setBackgroundColor(0xFFF7F5FF);content.setFitsSystemWindows(true);
        LinearLayout toolbar=new LinearLayout(activity);toolbar.setGravity(Gravity.CENTER_VERTICAL);toolbar.setPadding(dp(12),dp(6),dp(8),dp(6));toolbar.setBackgroundColor(Color.WHITE);
        TextView close=button("‹","문서함 닫기",v->dismiss());close.setTextSize(32);toolbar.addView(close,new LinearLayout.LayoutParams(dp(40),dp(48)));
        TextView title=label("문서함",22,0xFF3D4266);title.setTypeface(null,android.graphics.Typeface.BOLD);toolbar.addView(title,new LinearLayout.LayoutParams(0,dp(48),1));
        TextView add=button("＋ 새로 만들기","새로 만들기",this::newMenu);add.setTextSize(14);toolbar.addView(add,new LinearLayout.LayoutParams(dp(126),dp(48)));content.addView(toolbar,new LinearLayout.LayoutParams(-1,dp(64)));
        LinearLayout navigation=new LinearLayout(activity);navigation.setGravity(Gravity.CENTER_VERTICAL);navigation.setPadding(dp(8),0,dp(8),0);navigation.setBackgroundColor(Color.WHITE);
        TextView folders=button("☰ 폴더","폴더 트리 보기",v->{tree.setVisibility(tree.getVisibility()==View.VISIBLE?View.GONE:View.VISIBLE);shelf.post(this::refreshGrid);});foldersButton=folders;navigation.addView(folders,new LinearLayout.LayoutParams(dp(74),dp(36)));
        allButton=button("전체 문서","폴더와 관계없이 모든 문서 보기",v->{allMode=!allMode;selected.clear();selectionMode=false;refresh();});allButton.setTag("all_documents");LinearLayout.LayoutParams allParams=new LinearLayout.LayoutParams(dp(84),dp(36));allParams.setMargins(dp(4),0,dp(6),0);navigation.addView(allButton,allParams);
        HorizontalScrollView trail=new HorizontalScrollView(activity);trail.setHorizontalScrollBarEnabled(false);breadcrumb=new LinearLayout(activity);breadcrumb.setGravity(Gravity.CENTER_VERTICAL);trail.addView(breadcrumb,new HorizontalScrollView.LayoutParams(-2,-1));navigation.addView(trail,new LinearLayout.LayoutParams(0,dp(44),1));content.addView(navigation,new LinearLayout.LayoutParams(-1,dp(44)));
        LinearLayout controls=new LinearLayout(activity);controls.setGravity(Gravity.CENTER_VERTICAL);controls.setPadding(dp(10),0,dp(6),0);controls.setBackgroundColor(Color.WHITE);
        search=new EditText(activity);search.setSingleLine();search.setTextSize(13);search.setHint("이름 검색");search.setContentDescription("문서 이름 검색");search.setPadding(dp(6),0,dp(6),0);controls.addView(search,new LinearLayout.LayoutParams(0,dp(44),1));
        sortButton=button("정렬","파일 정렬",v->new AlertDialog.Builder(activity).setTitle("정렬").setSingleChoiceItems(LibraryRepository.SORT_NAMES,repository.sortMode(),(d,index)->{repository.sortMode(index);d.dismiss();refreshGrid();}).show());sortButton.setTextSize(13);controls.addView(sortButton,new LinearLayout.LayoutParams(dp(52),dp(44)));
        viewButton=button("보기","보기 방법",v->new AlertDialog.Builder(activity).setTitle("보기 방법").setSingleChoiceItems(LibraryRepository.VIEW_NAMES,repository.viewMode(),(d,index)->{repository.viewMode(index);d.dismiss();refreshGrid();}).show());viewButton.setTextSize(13);controls.addView(viewButton,new LinearLayout.LayoutParams(dp(52),dp(44)));
        selectButton=button("선택","문서 선택",v->{selectionMode=!selectionMode;selected.clear();refreshGrid();});selectButton.setTextSize(13);controls.addView(selectButton,new LinearLayout.LayoutParams(dp(52),dp(44)));
        TextView options=button("⋮","문서함 메뉴",this::libraryMenu);options.setTextSize(24);controls.addView(options,new LinearLayout.LayoutParams(dp(36),dp(44)));content.addView(controls,new LinearLayout.LayoutParams(-1,dp(44)));
        search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence q,int start,int count,int after){}public void onTextChanged(CharSequence q,int start,int before,int count){refreshGrid();}public void afterTextChanged(Editable e){}});
        body=new LinearLayout(activity);tree=new FolderTreeView(activity,repository,folder,this::selectFolder);tree.setFolderMenu(this::folderMenu);tree.setVisibility(activity.getResources().getConfiguration().screenWidthDp>=600?View.VISIBLE:View.GONE);body.addView(tree,new LinearLayout.LayoutParams(dp(178),-1));
        shelf=new ScrollView(activity);grid=new LinearLayout(activity);grid.setOrientation(LinearLayout.VERTICAL);grid.setPadding(dp(12),dp(10),dp(12),dp(24));shelf.addView(grid,new ScrollView.LayoutParams(-1,-2));body.addView(shelf,new LinearLayout.LayoutParams(0,-1,1));content.addView(body,new LinearLayout.LayoutParams(-1,0,1));
        selectionBar=new LinearLayout(activity);selectionBar.setGravity(Gravity.CENTER_VERTICAL);selectionBar.setPadding(dp(10),0,dp(10),0);selectionBar.setBackgroundColor(0xFFEDEBFF);selectionCount=label("0개",13,0xFF3D4266);selectionBar.addView(selectionCount,new LinearLayout.LayoutParams(0,dp(52),1));
        for(String action:new String[]{"전체","복사","이동","삭제"}){TextView command=button(action,"선택 문서 "+action,v->{List<File> files=new ArrayList<>(selected);if(action.equals("전체")){for(File item:allMode?repository.allDocuments(search.getText().toString()):repository.sorted(folder,search.getText().toString()))if(item.isFile())selected.add(item);refreshGrid();}else if(files.isEmpty())Toast.makeText(activity,"문서를 선택하세요",Toast.LENGTH_SHORT).show();else if(action.equals("삭제"))deleteDocuments(files);else chooseDestination(files,action.equals("이동"));});if(action.equals("삭제"))command.setTextColor(0xFFC74253);selectionBar.addView(command,new LinearLayout.LayoutParams(dp(48),dp(52)));}
        selectionBar.setVisibility(View.GONE);content.addView(selectionBar,new LinearLayout.LayoutParams(-1,dp(52)));content.setFocusableInTouchMode(true);content.requestFocus();setContentView(content);
        setOnDismissListener(d->{generation++;previews.shutdownNow();});shelf.addOnLayoutChangeListener((v,l,t,r,b,ol,ot,or,ob)->{if(r-l!=or-ol)shelf.post(this::refreshGrid);});refresh();
    }
    @Override public void show(){super.show();getWindow().setBackgroundDrawableResource(android.R.color.transparent);getWindow().setLayout(-1,-1);getWindow().setStatusBarColor(0xFFEEEBFF);getWindow().getDecorView().setSystemUiVisibility(getWindow().getDecorView().getSystemUiVisibility()|View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);getWindow().setNavigationBarColor(Color.WHITE);content.post(this::refreshGrid);}
    private void selectFolder(File selected){this.selected.clear();selectionMode=false;allMode=false;folder=selected;actions.selectedFolder(folder);refresh();}
    private void styleModeButtons(){allButton.setBackground(round(allMode?0xFFE6EAFF:0xFFF3F1FB,18));allButton.setTextColor(allMode?0xFF5062E0:0xFF3D4266);allButton.setTypeface(null,allMode?android.graphics.Typeface.BOLD:android.graphics.Typeface.NORMAL);foldersButton.setBackground(round(0xFFF3F1FB,18));foldersButton.setTextColor(0xFF3D4266);allButton.setTextSize(13);foldersButton.setTextSize(13);}
    private void refresh(){styleModeButtons();if(allMode){tree.select(folder);breadcrumb.removeAllViews();TextView crumb=label("전체 문서 · "+repository.allDocuments("").size()+"개",13,0xFF5B5F82);crumb.setPadding(dp(6),0,dp(6),0);breadcrumb.addView(crumb,new LinearLayout.LayoutParams(-2,dp(44)));refreshGrid();return;}
        tree.select(folder);breadcrumb.removeAllViews();List<File> path=new ArrayList<>();for(File p=folder;p!=null;p=p.getParentFile()){path.add(p);if(p.equals(repository.root))break;}Collections.reverse(path);for(File p:path){if(breadcrumb.getChildCount()>0)breadcrumb.addView(label(" › ",14,0xFF94A3B8));TextView item=button(p.equals(repository.root)?"문서함":p.getName(),"폴더로 이동 "+p.getName(),v->selectFolder(p));item.setTextSize(13);item.setPadding(dp(5),0,dp(5),0);breadcrumb.addView(item,new LinearLayout.LayoutParams(-2,dp(44)));}refreshGrid();}
    private void newMenu(View anchor){PopupMenu menu=new PopupMenu(activity,anchor);menu.getMenu().add("새 노트");menu.getMenu().add("폴더 만들기");menu.getMenu().add("파일 가져오기");menu.setOnMenuItemClickListener(item->{String title=item.getTitle().toString();if(title.equals("새 노트"))actions.newNote(folder,this::refresh);else if(title.equals("폴더 만들기"))createFolder(folder,()->{tree.reload();refresh();});else{actions.selectedFolder(folder);actions.importFiles(folder);dismiss();}return true;});menu.show();}
    private void refreshGrid(){
        if(previews.isShutdown()||grid==null)return;final int version=++generation;grid.removeAllViews();List<File> items=allMode?repository.allDocuments(search.getText().toString()):repository.sorted(folder,search.getText().toString());selectButton.setText(selectionMode?"완료":"선택");if(selectionBar!=null){selectionBar.setVisibility(selectionMode?View.VISIBLE:View.GONE);selectionCount.setText(selected.size()+"개");}heading=label(allMode?"전체 문서":folder.equals(repository.root)?"내 문서":folder.getName(),18,0xFF334155);heading.setTypeface(null,android.graphics.Typeface.BOLD);heading.setPadding(dp(3),dp(6),0,dp(14));grid.addView(heading);
        int mode=repository.viewMode();int columns=mode==2?1:Math.max(1,Math.min(5,(Math.max(shelf.getWidth(),dp(160))-dp(24))/dp(mode==1?112:150)));
        if(items.isEmpty()){TextView empty=label(search.getText().length()>0?"검색 결과가 없습니다":"아직 문서가 없습니다",15,0xFF64748B);empty.setGravity(Gravity.CENTER);grid.addView(empty,new LinearLayout.LayoutParams(-1,dp(100)));TextView add=button("＋ 새 노트","빈 폴더에 새 노트 만들기",v->actions.newNote(folder,this::refresh));grid.addView(add,new LinearLayout.LayoutParams(-1,dp(48)));return;}
        for(int i=0;i<items.size();i+=columns){LinearLayout row=new LinearLayout(activity);row.setGravity(Gravity.TOP);grid.addView(row,new LinearLayout.LayoutParams(-1,-2));for(int j=0;j<columns;j++){int index=i+j;LinearLayout.LayoutParams layout=new LinearLayout.LayoutParams(0,-2,1);layout.setMargins(dp(5),dp(4),dp(5),dp(14));if(index<items.size())row.addView(mode==2?listItem(items.get(index),version):card(items.get(index),version),layout);else row.addView(new View(activity),layout);}}
    }
    private View card(File file,int version){
        LinearLayout card=new LinearLayout(activity);card.setTag("document:"+file.getName());card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(9),dp(10),dp(9),dp(7));GradientDrawable surface=round(Color.WHITE,14);surface.setStroke(dp(1),0xFFE9E6F7);card.setBackground(surface);card.setElevation(dp(1));
        ImageView cover=new ImageView(activity);cover.setScaleType(ImageView.ScaleType.FIT_CENTER);cover.setBackground(round(file.isDirectory()?0xFFEDEBFF:0xFFF0F2F5,6));card.addView(cover,new LinearLayout.LayoutParams(-1,dp(repository.viewMode()==1?96:132)));cover.setContentDescription(file.getName()+" 미리보기");
        if(file.isDirectory()){cover.setImageDrawable(new FolderIconDrawable(repository.folderColor(file),dp(64)));cover.setBackground(round(pale(repository.folderColor(file)),6));cover.setPadding(dp(26),dp(18),dp(26),dp(18));}else{cover.setImageResource(R.drawable.ic_note_add);preview(file,cover,version);}
        LinearLayout nameRow=new LinearLayout(activity);nameRow.setGravity(Gravity.CENTER_VERTICAL);TextView name=label(file.getName().replaceFirst("(?i)\\.pdf$",""),14,0xFF1E293B);name.setMaxLines(2);name.setEllipsize(android.text.TextUtils.TruncateAt.END);name.setPadding(0,dp(6),0,0);nameRow.addView(name,new LinearLayout.LayoutParams(0,dp(46),1));
        if(selectionMode&&file.isFile()){CheckBox check=new CheckBox(activity);check.setChecked(selected.contains(file));check.setContentDescription("선택 "+file.getName());check.setOnClickListener(v->toggleSelected(file));nameRow.addView(check,new LinearLayout.LayoutParams(dp(36),dp(46)));}else{TextView more=button("⋮",file.getName()+" 메뉴",v->{if(file.isDirectory())folderMenu(file,v);else documentMenu(file,v);});more.setTextSize(25);nameRow.addView(more,new LinearLayout.LayoutParams(dp(32),dp(46)));}card.addView(nameRow);
        TextView type=label(file.isDirectory()?repository.list(file).size()+"개 항목":allMode?(repository.paper(file)!=null?"노트":"PDF")+" · "+(file.getParentFile().equals(repository.root)?"문서함":file.getParentFile().getName()):repository.paper(file)!=null?"노트":"PDF",11,0xFF94A3B8);card.addView(type,new LinearLayout.LayoutParams(-1,dp(22)));
        View.OnClickListener open=v->openOrSelect(file);cover.setOnClickListener(open);name.setOnClickListener(open);card.setOnClickListener(open);card.setOnLongClickListener(v->{if(file.isDirectory())folderMenu(file,v);else{selectionMode=true;selected.add(file);refreshGrid();}return true;});return card;
    }
    private void preview(File file,ImageView cover,int version){
        String key=file.getAbsolutePath()+":"+file.lastModified()+":"+AnnotationStore.modified(activity,Uri.fromFile(file));Bitmap cached=covers.get(key);if(cached!=null){cover.setImageBitmap(cached);return;}
        previews.execute(()->{if(version!=generation)return;try(ParcelFileDescriptor descriptor=ParcelFileDescriptor.open(file,ParcelFileDescriptor.MODE_READ_ONLY);PdfRenderer renderer=new PdfRenderer(descriptor);PdfRenderer.Page page=renderer.openPage(0)){
            float scale=Math.min(240f/page.getWidth(),360f/page.getHeight());Bitmap bitmap=Bitmap.createBitmap(Math.max(1,Math.round(page.getWidth()*scale)),Math.max(1,Math.round(page.getHeight()*scale)),Bitmap.Config.ARGB_8888);bitmap.eraseColor(Color.WHITE);Matrix matrix=new Matrix();matrix.postScale(scale,scale);page.render(bitmap,null,matrix,PdfRenderer.Page.RENDER_MODE_FOR_DISPLAY);AnnotationStore store=new AnnotationStore(activity);store.open(Uri.fromFile(file));AnnotationPainter.all(activity,new Canvas(bitmap),new RectF(0,0,bitmap.getWidth(),bitmap.getHeight()),store,0);
            covers.put(key,bitmap);activity.runOnUiThread(()->{if(isShowing()&&version==generation)cover.setImageBitmap(bitmap);});
        }catch(Exception ignored){}});
    }
    private void documentMenu(File file,View anchor){PopupMenu menu=new PopupMenu(activity,anchor);for(String name:new String[]{"이름 변경","복사","이동","삭제"})menu.getMenu().add(name);menu.setOnMenuItemClickListener(item->{if(item.getTitle().equals("이름 변경"))rename(file);else if(item.getTitle().equals("삭제"))deleteDocuments(Collections.singletonList(file));else chooseDestination(Collections.singletonList(file),item.getTitle().equals("이동"));return true;});menu.show();}
    private void rename(File file){EditText input=new EditText(activity);input.setSingleLine();input.setText(file.getName().replaceFirst("(?i)\\.pdf$",""));input.selectAll();AlertDialog dialog=new AlertDialog.Builder(activity).setTitle("이름 변경").setView(input).setPositiveButton("저장",null).setNegativeButton("취소",null).create();dialog.setOnShowListener(d->dialog.getButton(-1).setOnClickListener(v->{try{String name=NotebookFiles.pdfName(input.getText().toString());if(!name.equals(file.getName())&&new File(file.getParentFile(),name).exists())throw new java.io.IOException("같은 이름의 PDF가 있습니다");dialog.dismiss();transfer(file,file.getParentFile(),name,true);}catch(Exception error){input.setError(error.getMessage());}}));dialog.show();}
    private void chooseDestination(List<File> files,boolean move){
        LinearLayout panel=new LinearLayout(activity);panel.setOrientation(LinearLayout.VERTICAL);FolderTreeView picker=new FolderTreeView(activity,repository,folder,f->{});panel.addView(picker,new LinearLayout.LayoutParams(-1,dp(340)));TextView add=button("＋ 폴더 만들기","대상 폴더 만들기",v->createFolder(picker.selected(),picker::reload));panel.addView(add,new LinearLayout.LayoutParams(-1,dp(44)));
        new AlertDialog.Builder(activity).setTitle(move?"이동할 폴더":"복사할 폴더").setView(panel).setPositiveButton(move?"이곳으로 이동":"이곳에 복사",(d,w)->transferMany(files,picker.selected(),move)).setNegativeButton("취소",null).show();
    }
    private void transfer(File file,File target,String name,boolean move){if(busy)return;busy=true;ProgressDialog progress=ProgressDialog.show(activity,"",move?"문서를 이동하는 중…":"문서를 복사하는 중…",true,false);new Thread(()->{try{File saved=repository.transfer(file,target,name,move);activity.runOnUiThread(()->{busy=false;progress.dismiss();actions.changed(file,saved,move);refresh();Toast.makeText(activity,move?"저장했습니다":"복사했습니다",Toast.LENGTH_SHORT).show();});}catch(Exception error){activity.runOnUiThread(()->{busy=false;progress.dismiss();Toast.makeText(activity,error.getMessage(),Toast.LENGTH_LONG).show();});}},"library-transfer").start();}
    private void openOrSelect(File file){if(file.isDirectory())selectFolder(file);else if(selectionMode)toggleSelected(file);else{dismiss();actions.open(file);}}
    private void toggleSelected(File file){if(!selected.remove(file))selected.add(file);refreshGrid();}
    private View listItem(File file,int version){
        LinearLayout row=new LinearLayout(activity);row.setTag("document:"+file.getName());row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(10),dp(8),dp(4),dp(8));row.setBackground(round(Color.WHITE,10));
        ImageView image=new ImageView(activity);image.setScaleType(ImageView.ScaleType.FIT_CENTER);image.setBackground(round(file.isDirectory()?pale(repository.folderColor(file)):0xFFF0F2F5,5));row.addView(image,new LinearLayout.LayoutParams(dp(52),dp(64)));if(file.isDirectory()){image.setImageDrawable(new FolderIconDrawable(repository.folderColor(file),dp(40)));image.setPadding(dp(10),dp(10),dp(10),dp(10));}else{image.setImageResource(R.drawable.ic_note_add);preview(file,image,version);}
        TextView name=label(file.getName().replaceFirst("(?i)\\.pdf$",""),14,0xFF1E293B);name.setMaxLines(2);name.setEllipsize(android.text.TextUtils.TruncateAt.END);name.setPadding(dp(12),0,dp(4),0);row.addView(name,new LinearLayout.LayoutParams(0,dp(64),1));
        if(selectionMode&&file.isFile()){CheckBox check=new CheckBox(activity);check.setChecked(selected.contains(file));check.setContentDescription("선택 "+file.getName());check.setOnClickListener(v->toggleSelected(file));row.addView(check,new LinearLayout.LayoutParams(dp(40),dp(56)));}else{TextView more=button("⋮",file.getName()+" 메뉴",v->{if(file.isDirectory())folderMenu(file,v);else documentMenu(file,v);});more.setTextSize(24);row.addView(more,new LinearLayout.LayoutParams(dp(36),dp(56)));}
        row.setOnClickListener(v->openOrSelect(file));row.setOnLongClickListener(v->{if(file.isDirectory())folderMenu(file,v);else{selectionMode=true;selected.add(file);refreshGrid();}return true;});return row;
    }
    private void libraryMenu(View anchor){PopupMenu menu=new PopupMenu(activity,anchor);menu.getMenu().add("폴더 색상");menu.getMenu().add("휴지통");menu.setOnMenuItemClickListener(item->{if(item.getTitle().equals("휴지통"))showTrash();else chooseFolderColor(folder);return true;});menu.show();}
    private void folderMenu(File folder,View anchor){PopupMenu menu=new PopupMenu(activity,anchor);menu.getMenu().add("폴더 색상");menu.getMenu().add("하위 폴더 만들기");menu.setOnMenuItemClickListener(item->{if(item.getTitle().equals("폴더 색상"))chooseFolderColor(folder);else createFolder(folder,()->{tree.reload();refresh();});return true;});menu.show();}
    private void chooseFolderColor(File folder){int selected=0;for(int i=0;i<LibraryRepository.FOLDER_COLORS.length;i++)if(LibraryRepository.FOLDER_COLORS[i]==repository.folderColor(folder))selected=i;
        new AlertDialog.Builder(activity).setTitle("폴더 색상 · "+(folder.equals(repository.root)?"문서함":folder.getName())).setSingleChoiceItems(LibraryRepository.FOLDER_COLOR_NAMES,selected,(d,index)->{repository.folderColor(folder,LibraryRepository.FOLDER_COLORS[index]);d.dismiss();tree.reload();refreshGrid();}).setNegativeButton("취소",null).show();}
    private void transferMany(List<File> files,File destination,boolean move){if(busy)return;busy=true;ProgressDialog progress=ProgressDialog.show(activity,"",move?"문서를 이동하는 중…":"문서를 복사하는 중…",true,false);new Thread(()->{List<File[]> changes=new ArrayList<>();String error="";for(File file:files)try{changes.add(new File[]{file,repository.transfer(file,destination,file.getName(),move)});}catch(Exception failure){error=failure.getMessage();}final String reason=error;activity.runOnUiThread(()->{busy=false;progress.dismiss();for(File[] change:changes)actions.changed(change[0],change[1],move);selected.clear();selectionMode=false;refresh();Toast.makeText(activity,reason.isEmpty()?changes.size()+"개 "+(move?"이동했습니다":"복사했습니다"):changes.size()+"개 처리 · "+reason,Toast.LENGTH_LONG).show();});},"library-bulk-transfer").start();}
    private void deleteDocuments(List<File> files){new AlertDialog.Builder(activity).setTitle("문서 삭제").setMessage(files.size()+"개 문서를 휴지통으로 이동할까요?").setPositiveButton("삭제",(d,w)->{if(busy)return;busy=true;ProgressDialog progress=ProgressDialog.show(activity,"","휴지통으로 이동하는 중…",true,false);new Thread(()->{List<File> removed=new ArrayList<>();String error="";for(File file:files)try{repository.trash(file);removed.add(file);}catch(Exception failure){error=failure.getMessage();}final String reason=error;activity.runOnUiThread(()->{busy=false;progress.dismiss();actions.removed(removed);selected.clear();selectionMode=false;refresh();Toast.makeText(activity,reason.isEmpty()?removed.size()+"개 삭제 · 휴지통에서 복원할 수 있습니다":removed.size()+"개 삭제 · "+reason,Toast.LENGTH_LONG).show();});},"library-delete").start();}).setNegativeButton("취소",null).show();}
    private void showTrash(){List<LibraryRepository.TrashItem> items=repository.trashItems();if(items.isEmpty()){new AlertDialog.Builder(activity).setTitle("휴지통").setMessage("휴지통이 비어 있습니다").setPositiveButton("닫기",null).show();return;}String[] names=new String[items.size()];for(int i=0;i<names.length;i++)names[i]=items.get(i).name;new AlertDialog.Builder(activity).setTitle("휴지통 · "+items.size()).setItems(names,(d,index)->new AlertDialog.Builder(activity).setTitle(items.get(index).name).setPositiveButton("복원",(restore,w)->{if(busy)return;busy=true;new Thread(()->{try{repository.restore(items.get(index));activity.runOnUiThread(()->{busy=false;refresh();Toast.makeText(activity,"원래 폴더로 복원했습니다",Toast.LENGTH_SHORT).show();});}catch(Exception error){activity.runOnUiThread(()->{busy=false;Toast.makeText(activity,error.getMessage(),Toast.LENGTH_LONG).show();});}},"library-restore").start();}).setNegativeButton("취소",null).show()).setNegativeButton("닫기",null).show();}
    private int pale(int color){return Color.rgb((Color.red(color)+255*6)/7,(Color.green(color)+255*6)/7,(Color.blue(color)+255*6)/7);}
    private void createFolder(File parent,Runnable done){EditText input=new EditText(activity);input.setHint("폴더 이름");input.setSingleLine();AlertDialog dialog=new AlertDialog.Builder(activity).setTitle("폴더 만들기").setView(input).setPositiveButton("만들기",null).setNegativeButton("취소",null).create();dialog.setOnShowListener(d->dialog.getButton(-1).setOnClickListener(v->{try{repository.createFolder(parent,input.getText().toString());dialog.dismiss();done.run();}catch(Exception error){input.setError(error.getMessage());}}));dialog.show();}
    private TextView button(String text,String description,View.OnClickListener click){TextView button=label(text,15,0xFF6C7BEA);button.setGravity(Gravity.CENTER);button.setContentDescription(description);button.setOnClickListener(click);button.setBackgroundResource(android.R.drawable.list_selector_background);return button;}
    private TextView label(String text,int size,int color){TextView view=new TextView(activity);view.setText(text);view.setTextSize(size);view.setTextColor(color);view.setGravity(Gravity.CENTER_VERTICAL);return view;}
    private GradientDrawable round(int color,int radius){GradientDrawable bg=new GradientDrawable();bg.setColor(color);bg.setCornerRadius(dp(radius));return bg;}
    private int dp(float n){return Math.round(n*activity.getResources().getDisplayMetrics().density);}
}
