package com.hdlee.pdfnote;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.graphics.pdf.PdfRenderer;
import android.net.Uri;
import android.os.*;
import android.provider.OpenableColumns;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.util.*;

public class MainActivity extends Activity implements PdfPageView.Listener {
    private static final class DocumentSession {
        Uri uri; String title; ParcelFileDescriptor descriptor; PdfRenderer renderer;
        AnnotationStore store; int page;
        final Deque<AnnotationStore.InkStroke> redoStrokes=new ArrayDeque<>();
    }
    private static final int OPEN_PDF=10, EXPORT_JSON=11, NAVY=0xFF173B63, ACCENT=0xFF2563EB;
    private PdfRenderer renderer; private ParcelFileDescriptor descriptor; private Uri documentUri;
    private String documentTitle="PDF"; private int currentPage, selectedColor=0x66FFDE59;
    private PdfPageView pageView; private TextView titleView,pageLabel; private Button highlightButton;
    private ImageButton bookmarkButton,colorButton,memoButton,inkButton,fullscreenExit; private LinearLayout header,bottomBar;
    private FrameLayout root; private AnnotationStore store; private boolean highlightMode,memoMode,outlineMode,fullscreen;
    private boolean verticalPageSwipe;
    private final List<DocumentSession> sessions=new ArrayList<>(); private DocumentSession activeSession;
    private LinearLayout tabRow,thumbnailList; private HorizontalScrollView tabStrip; private ScrollView thumbnailPanel;
    private int thumbnailGeneration; private boolean sidebarVisible;
    private int inkMode,inkColor=0xFF172033; private float inkWidth=0.004f;
    private SharedPreferences recentPrefs;

    @Override protected void onCreate(Bundle state){super.onCreate(state);recentPrefs=getSharedPreferences("recent_documents",MODE_PRIVATE);verticalPageSwipe=recentPrefs.getBoolean("vertical_page_swipe",false);buildUi();pageView.setVerticalPageSwipe(verticalPageSwipe);Uri u=getIntent().getData();if(u!=null)openPdf(u);else showWelcome();}
    private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
    private GradientDrawable round(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
    private ImageButton icon(int image,String label,int tint,View.OnClickListener click){ImageButton b=new ImageButton(this);b.setImageResource(image);b.setColorFilter(tint);b.setContentDescription(label);b.setBackgroundColor(Color.TRANSPARENT);b.setScaleType(ImageView.ScaleType.CENTER);b.setPadding(dp(12),dp(12),dp(12),dp(12));b.setOnClickListener(click);return b;}

    private void buildUi(){
        root=new FrameLayout(this);root.setBackgroundColor(0xFFF1F3F5);LinearLayout content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);root.addView(content,new FrameLayout.LayoutParams(-1,-1));
        header=new LinearLayout(this);header.setGravity(Gravity.CENTER_VERTICAL);header.setPadding(dp(4),0,dp(4),0);header.setBackgroundColor(NAVY);
        header.addView(icon(R.drawable.ic_folder_open,"PDF 열기",Color.WHITE,v->choosePdf()),new LinearLayout.LayoutParams(dp(52),dp(56)));
        titleView=new TextView(this);titleView.setTextColor(Color.WHITE);titleView.setTextSize(19);titleView.setSingleLine();titleView.setGravity(Gravity.CENTER_VERTICAL);titleView.setPadding(dp(8),0,dp(8),0);header.addView(titleView,new LinearLayout.LayoutParams(0,dp(56),1));
        header.addView(icon(R.drawable.ic_thumbnails,"페이지 목록",Color.WHITE,v->toggleSidebar()),new LinearLayout.LayoutParams(dp(48),dp(56)));
        header.addView(icon(R.drawable.ic_outline,"개요",Color.WHITE,v->showOutlineList()),new LinearLayout.LayoutParams(dp(48),dp(56)));
        header.addView(icon(R.drawable.ic_fullscreen,"전체 화면",Color.WHITE,v->toggleFullscreen()),new LinearLayout.LayoutParams(dp(48),dp(56)));
        header.addView(icon(R.drawable.ic_more_vert,"도구",Color.WHITE,v->showTools()),new LinearLayout.LayoutParams(dp(48),dp(56)));content.addView(header,new LinearLayout.LayoutParams(-1,dp(56)));
        tabStrip=new HorizontalScrollView(this);tabStrip.setHorizontalScrollBarEnabled(false);tabStrip.setBackgroundColor(0xFFF8FAFC);tabRow=new LinearLayout(this);tabRow.setGravity(Gravity.CENTER_VERTICAL);tabRow.setPadding(dp(6),dp(4),dp(6),dp(4));tabStrip.addView(tabRow,new HorizontalScrollView.LayoutParams(-2,-1));content.addView(tabStrip,new LinearLayout.LayoutParams(-1,dp(44)));
        LinearLayout viewerRow=new LinearLayout(this);viewerRow.setOrientation(LinearLayout.HORIZONTAL);
        thumbnailPanel=new ScrollView(this);thumbnailPanel.setBackgroundColor(0xFFF1F5F9);thumbnailPanel.setVisibility(View.GONE);thumbnailList=new LinearLayout(this);thumbnailList.setOrientation(LinearLayout.VERTICAL);thumbnailList.setPadding(dp(7),dp(8),dp(7),dp(8));thumbnailPanel.addView(thumbnailList,new ScrollView.LayoutParams(-1,-2));viewerRow.addView(thumbnailPanel,new LinearLayout.LayoutParams(dp(116),-1));
        pageView=new PdfPageView(this,this);viewerRow.addView(pageView,new LinearLayout.LayoutParams(0,-1,1));content.addView(viewerRow,new LinearLayout.LayoutParams(-1,0,1));
        bottomBar=new LinearLayout(this);bottomBar.setGravity(Gravity.CENTER_VERTICAL);bottomBar.setPadding(dp(4),dp(4),dp(4),dp(4));bottomBar.setBackgroundColor(Color.WHITE);bottomBar.setElevation(dp(10));
        bottomBar.addView(icon(R.drawable.ic_chevron_left,"이전 페이지",NAVY,v->showPage(currentPage-1)),new LinearLayout.LayoutParams(dp(44),dp(56)));
        pageLabel=new TextView(this);pageLabel.setGravity(Gravity.CENTER);pageLabel.setTextColor(0xFF475569);pageLabel.setTextSize(14);pageLabel.setSingleLine();pageLabel.setBackground(round(0xFFF1F5F9,18));LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(0,dp(38),1);pp.setMargins(dp(2),0,dp(2),0);bottomBar.addView(pageLabel,pp);
        bottomBar.addView(icon(R.drawable.ic_chevron_right,"다음 페이지",NAVY,v->showPage(currentPage+1)),new LinearLayout.LayoutParams(dp(44),dp(56)));
        highlightButton=new Button(this);highlightButton.setText("하이라이트");highlightButton.setTextSize(13);highlightButton.setTextColor(NAVY);highlightButton.setAllCaps(false);highlightButton.setCompoundDrawablesWithIntrinsicBounds(R.drawable.ic_highlight,0,0,0);highlightButton.setCompoundDrawablePadding(dp(4));highlightButton.setBackground(round(0xFFEFF6FF,18));highlightButton.setOnClickListener(v->toggleHighlight());LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(-2,dp(42));hp.setMargins(dp(4),0,dp(4),0);bottomBar.addView(highlightButton,hp);
        colorButton=icon(R.drawable.ic_palette,"하이라이트 색상",NAVY,v->chooseColor());bottomBar.addView(colorButton,new LinearLayout.LayoutParams(dp(46),dp(46)));updateColorButton();
        memoButton=icon(R.drawable.ic_note_add,"메모 추가",NAVY,v->toggleMemoMode());bottomBar.addView(memoButton,new LinearLayout.LayoutParams(dp(44),dp(56)));
        inkButton=icon(R.drawable.ic_ink,"필기도구",NAVY,v->showInkTools());bottomBar.addView(inkButton,new LinearLayout.LayoutParams(dp(44),dp(56)));
        bookmarkButton=icon(R.drawable.ic_star_outline,"즐겨찾기",NAVY,v->toggleBookmark());bottomBar.addView(bookmarkButton,new LinearLayout.LayoutParams(dp(48),dp(56)));content.addView(bottomBar,new LinearLayout.LayoutParams(-1,dp(64)));
        fullscreenExit=icon(R.drawable.ic_fullscreen_exit,"전체 화면 종료",Color.WHITE,v->toggleFullscreen());fullscreenExit.setBackground(round(0xAA0F172A,24));fullscreenExit.setVisibility(View.GONE);FrameLayout.LayoutParams ep=new FrameLayout.LayoutParams(dp(48),dp(48),Gravity.TOP|Gravity.END);ep.setMargins(0,dp(12),dp(12),0);root.addView(fullscreenExit,ep);
        root.setOnApplyWindowInsetsListener((v,insets)->{int top,bottom;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets b=insets.getInsets(WindowInsets.Type.systemBars());top=b.top;bottom=b.bottom;}else{top=insets.getSystemWindowInsetTop();bottom=insets.getSystemWindowInsetBottom();}if(!fullscreen){header.setPadding(dp(4),top,dp(4),0);header.getLayoutParams().height=dp(56)+top;bottomBar.setPadding(dp(4),dp(4),dp(4),dp(4)+bottom);bottomBar.getLayoutParams().height=dp(64)+bottom;}return insets;});setContentView(root);
    }
    private void showWelcome(){titleView.setText("PDF Note");pageLabel.setText("PDF를 열어 시작하세요");String u=recentPrefs.getString("last_uri",null);if(u!=null)new AlertDialog.Builder(this).setTitle("최근 문서").setMessage(recentPrefs.getString("last_title","최근 PDF")+"을 다시 여시겠습니까?").setPositiveButton("열기",(d,w)->openPdf(Uri.parse(u))).setNegativeButton("다른 문서",(d,w)->choosePdf()).show();}
    private void choosePdf(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/pdf");startActivityForResult(i,OPEN_PDF);}
    @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;Uri u=data.getData();if(req==OPEN_PDF){try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(SecurityException ignored){}openPdf(u);}else if(req==EXPORT_JSON){try(OutputStream out=getContentResolver().openOutputStream(u)){if(out!=null)out.write(store.exportJson(documentUri,documentTitle).getBytes());toast("주석을 내보냈습니다");}catch(Exception e){toast("내보내기 실패: "+e.getMessage());}}}
    private void openPdf(Uri u){for(DocumentSession s:sessions)if(s.uri.equals(u)){switchDocument(s);return;}DocumentSession s=new DocumentSession();try{s.descriptor=getContentResolver().openFileDescriptor(u,"r");if(s.descriptor==null)throw new IOException("파일을 읽을 수 없습니다");s.renderer=new PdfRenderer(s.descriptor);s.uri=u;s.title=queryName(u);s.store=new AnnotationStore(this);s.store.open(u);sessions.add(s);recentPrefs.edit().putString("last_uri",u.toString()).putString("last_title",s.title).apply();switchDocument(s);}catch(Exception e){if(s.renderer!=null)s.renderer.close();if(s.descriptor!=null)try{s.descriptor.close();}catch(IOException ignored){}toast("PDF 열기 실패: "+e.getMessage());if(sessions.isEmpty())showWelcome();}}
    private void switchDocument(DocumentSession s){if(activeSession!=null)activeSession.page=currentPage;activeSession=s;renderer=s.renderer;descriptor=s.descriptor;documentUri=s.uri;documentTitle=s.title;store=s.store;titleView.setText(documentTitle);highlightMode=memoMode=outlineMode=false;inkMode=0;pageView.setHighlightMode(false,selectedColor);pageView.setMemoMode(false);pageView.setOutlineMode(false);pageView.setInkTool(0,inkColor,inkWidth);updateToolStates();updateInkButton();updateTabs();showPage(Math.min(s.page,renderer.getPageCount()-1));rebuildThumbnails();}
    private void closeDocument(DocumentSession s){int oldIndex=sessions.indexOf(s);sessions.remove(s);if(s.renderer!=null)s.renderer.close();if(s.descriptor!=null)try{s.descriptor.close();}catch(IOException ignored){}if(s==activeSession){activeSession=null;if(sessions.isEmpty()){renderer=null;descriptor=null;documentUri=null;store=null;pageView.clearPage();thumbnailList.removeAllViews();updateTabs();showWelcome();}else switchDocument(sessions.get(Math.max(0,Math.min(oldIndex,sessions.size()-1))));}else updateTabs();}
    private void updateTabs(){tabRow.removeAllViews();for(DocumentSession s:sessions){LinearLayout chip=new LinearLayout(this);chip.setGravity(Gravity.CENTER_VERTICAL);chip.setPadding(dp(10),0,dp(2),0);chip.setBackground(round(s==activeSession?0xFFDCEAFE:0xFFEFF2F6,14));TextView name=new TextView(this);name.setText(s.title);name.setSingleLine();name.setEllipsize(android.text.TextUtils.TruncateAt.END);name.setTextColor(s==activeSession?ACCENT:0xFF475569);name.setTextSize(13);name.setOnClickListener(v->switchDocument(s));chip.addView(name,new LinearLayout.LayoutParams(dp(132),dp(34)));TextView close=new TextView(this);close.setText("×");close.setGravity(Gravity.CENTER);close.setTextSize(21);close.setTextColor(0xFF64748B);close.setContentDescription(s.title+" 닫기");close.setOnClickListener(v->closeDocument(s));chip.addView(close,new LinearLayout.LayoutParams(dp(34),dp(34)));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-2,dp(34));cp.setMargins(dp(3),0,dp(3),0);tabRow.addView(chip,cp);}TextView add=new TextView(this);add.setText("＋");add.setGravity(Gravity.CENTER);add.setTextSize(24);add.setTextColor(ACCENT);add.setContentDescription("PDF 추가");add.setOnClickListener(v->choosePdf());tabRow.addView(add,new LinearLayout.LayoutParams(dp(44),dp(34)));}
    private String queryName(Uri u){try(android.database.Cursor c=getContentResolver().query(u,null,null,null,null)){if(c!=null&&c.moveToFirst()){int i=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(i>=0)return c.getString(i);}}catch(Exception ignored){}return u.getLastPathSegment()==null?"PDF":u.getLastPathSegment();}
    private void toggleSidebar(){sidebarVisible=!sidebarVisible;thumbnailPanel.setVisibility(sidebarVisible?View.VISIBLE:View.GONE);if(sidebarVisible)rebuildThumbnails();}
    private void rebuildThumbnails(){final int generation=++thumbnailGeneration;thumbnailList.removeAllViews();if(!sidebarVisible||renderer==null)return;for(int i=0;i<renderer.getPageCount();i++){final int page=i;LinearLayout item=new LinearLayout(this);item.setTag(page);item.setOrientation(LinearLayout.VERTICAL);item.setGravity(Gravity.CENTER);item.setPadding(dp(4),dp(5),dp(4),dp(7));ImageView preview=new ImageView(this);preview.setTag("image");preview.setScaleType(ImageView.ScaleType.FIT_CENTER);preview.setBackgroundColor(Color.WHITE);item.addView(preview,new LinearLayout.LayoutParams(dp(94),dp(126)));TextView number=new TextView(this);number.setText(String.valueOf(i+1));number.setGravity(Gravity.CENTER);number.setTextSize(12);number.setTextColor(0xFF475569);item.addView(number,new LinearLayout.LayoutParams(-1,dp(24)));item.setOnClickListener(v->showPage(page));thumbnailList.addView(item,new LinearLayout.LayoutParams(-1,dp(160)));}updateThumbnailSelection();renderThumbnail(0,generation,activeSession);}
    private void renderThumbnail(int index,int generation,DocumentSession session){if(generation!=thumbnailGeneration||session!=activeSession||renderer==null||index>=renderer.getPageCount())return;thumbnailList.post(()->{if(generation!=thumbnailGeneration||session!=activeSession)return;try(PdfRenderer.Page page=renderer.openPage(index)){int width=188;float ratio=(float)width/page.getWidth();Bitmap image=Bitmap.createBitmap(width,Math.max(1,(int)(page.getHeight()*ratio)),Bitmap.Config.ARGB_8888);image.eraseColor(Color.WHITE);Matrix matrix=new Matrix();matrix.postScale(ratio,ratio);page.render(image,null,matrix,PdfRenderer.Page.RENDER_MODE_FOR_DISPLAY);View item=thumbnailList.findViewWithTag(index);if(item instanceof LinearLayout){View child=((LinearLayout)item).getChildAt(0);if(child instanceof ImageView)((ImageView)child).setImageBitmap(image);}}catch(Exception ignored){}renderThumbnail(index+1,generation,session);});}
    private void updateThumbnailSelection(){for(int i=0;i<thumbnailList.getChildCount();i++){View v=thumbnailList.getChildAt(i);Object tag=v.getTag();boolean selected=tag instanceof Integer&&((Integer)tag)==currentPage;GradientDrawable bg=round(selected?0xFFDCEAFE:Color.TRANSPARENT,8);if(selected)bg.setStroke(dp(2),ACCENT);v.setBackground(bg);}if(sidebarVisible&&currentPage<thumbnailList.getChildCount())thumbnailList.getChildAt(currentPage).post(()->thumbnailPanel.smoothScrollTo(0,Math.max(0,thumbnailList.getChildAt(currentPage).getTop()-dp(16))));}
    private void showPage(int index){if(renderer==null||index<0||index>=renderer.getPageCount())return;currentPage=index;if(activeSession!=null)activeSession.page=index;try(PdfRenderer.Page page=renderer.openPage(index)){int width=Math.max(1080,getResources().getDisplayMetrics().widthPixels*2);float ratio=Math.min(2.5f,(float)width/page.getWidth());Bitmap image=Bitmap.createBitmap((int)(page.getWidth()*ratio),(int)(page.getHeight()*ratio),Bitmap.Config.ARGB_8888);image.eraseColor(Color.WHITE);Matrix m=new Matrix();m.postScale(ratio,ratio);page.render(image,null,m,PdfRenderer.Page.RENDER_MODE_FOR_DISPLAY);pageView.showPage(image,index,store.marks,store.strokes);pageLabel.setText((index+1)+" / "+renderer.getPageCount());updateBookmarkButton();updateThumbnailSelection();}}
    private void toggleHighlight(){if(renderer==null)return;highlightMode=!highlightMode;memoMode=outlineMode=false;stopInk();updateToolStates();pageView.setMemoMode(false);pageView.setOutlineMode(false);pageView.setHighlightMode(highlightMode,selectedColor);toast(highlightMode?"문장을 따라 좌우로 드래그하세요":"하이라이트를 종료했습니다");}
    private void toggleMemoMode(){if(renderer==null)return;memoMode=!memoMode;highlightMode=outlineMode=false;stopInk();updateToolStates();pageView.setHighlightMode(false,selectedColor);pageView.setOutlineMode(false);pageView.setMemoMode(memoMode);toast(memoMode?"메모를 놓을 위치를 탭하세요":"메모 추가를 종료했습니다");}
    private void toggleOutlineMode(){if(renderer==null)return;outlineMode=!outlineMode;highlightMode=memoMode=false;stopInk();pageView.setHighlightMode(false,selectedColor);pageView.setMemoMode(false);pageView.setOutlineMode(outlineMode);updateToolStates();toast(outlineMode?"개요로 저장할 정확한 위치를 탭하세요":"개요 지점 선택을 종료했습니다");}
    private void updateToolStates(){highlightButton.setText(highlightMode?"하이라이트 ✓":"하이라이트");highlightButton.setTextColor(highlightMode?Color.WHITE:NAVY);highlightButton.setBackground(round(highlightMode?ACCENT:0xFFEFF6FF,18));memoButton.setColorFilter(memoMode?Color.WHITE:NAVY);memoButton.setBackground(memoMode?round(ACCENT,22):round(Color.TRANSPARENT,22));}
    private void stopInk(){inkMode=0;pageView.setInkTool(0,inkColor,inkWidth);updateInkButton();}
    private void setInkMode(int mode){if(renderer==null)return;inkMode=mode;highlightMode=memoMode=outlineMode=false;pageView.setHighlightMode(false,selectedColor);pageView.setMemoMode(false);pageView.setOutlineMode(false);pageView.setInkTool(mode,inkColor,inkWidth);updateToolStates();updateInkButton();toast(mode==1?"S펜으로 필기하세요. 손가락은 화면 이동에 사용됩니다":mode==2?"S펜으로 지울 획을 터치하세요":"필기 모드를 종료했습니다");}
    private void updateInkButton(){if(inkButton==null)return;inkButton.setColorFilter(inkMode==0?NAVY:Color.WHITE);inkButton.setBackground(inkMode==0?round(Color.TRANSPARENT,22):round(inkMode==2?0xFFDC2626:ACCENT,22));inkButton.setContentDescription(inkMode==1?"펜 사용 중":inkMode==2?"지우개 사용 중":"필기도구");}
    private void showInkTools(){if(renderer==null){toast("PDF를 먼저 여세요");return;}String active=inkMode==1?" ✓":inkMode==2?" ✓":"";String[] tools={"펜"+(inkMode==1?active:""),"지우개"+(inkMode==2?active:""),"필기 종료","실행 취소","다시 실행","펜 색상","펜 굵기","사용 안내"};new AlertDialog.Builder(this).setTitle("S펜 필기도구").setItems(tools,(d,w)->{if(w==0)setInkMode(1);else if(w==1)setInkMode(2);else if(w==2)setInkMode(0);else if(w==3)undoInk();else if(w==4)redoInk();else if(w==5)chooseInkColor();else if(w==6)chooseInkWidth();else showInkHelp();}).show();}
    private void chooseInkColor(){String[] names={"차콜","블루","레드","그린","퍼플"};int[] colors={0xFF172033,0xFF2563EB,0xFFDC2626,0xFF16835B,0xFF7C3AED};new AlertDialog.Builder(this).setTitle("펜 색상").setSingleChoiceItems(names,indexOf(colors,inkColor),(d,w)->{inkColor=colors[w];pageView.setInkTool(inkMode,inkColor,inkWidth);d.dismiss();}).setNegativeButton("취소",null).show();}
    private int indexOf(int[] values,int value){for(int i=0;i<values.length;i++)if(values[i]==value)return i;return 0;}
    private void chooseInkWidth(){String[] names={"가늘게","보통","굵게","아주 굵게"};float[] widths={0.0022f,0.004f,0.0065f,0.009f};int checked=0;for(int i=0;i<widths.length;i++)if(Math.abs(widths[i]-inkWidth)<0.0001f)checked=i;final int selected=checked;new AlertDialog.Builder(this).setTitle("기본 펜 굵기").setSingleChoiceItems(names,selected,(d,w)->{inkWidth=widths[w];pageView.setInkTool(inkMode,inkColor,inkWidth);d.dismiss();}).setNegativeButton("취소",null).show();}
    private void undoInk(){if(store==null)return;for(int i=store.strokes.size()-1;i>=0;i--){AnnotationStore.InkStroke s=store.strokes.get(i);if(s.page==currentPage){store.strokes.remove(i);activeSession.redoStrokes.push(s);store.save();pageView.invalidate();toast("마지막 필기를 취소했습니다");return;}}toast("취소할 필기가 없습니다");}
    private void redoInk(){if(activeSession==null||activeSession.redoStrokes.isEmpty()){toast("다시 실행할 필기가 없습니다");return;}AnnotationStore.InkStroke s=activeSession.redoStrokes.pop();store.strokes.add(s);store.save();if(s.page!=currentPage)showPage(s.page);else pageView.invalidate();}
    private void showInkHelp(){new AlertDialog.Builder(this).setTitle("S펜 필기 안내").setMessage("• S펜: 필기 또는 지우개\n• 손가락: 확대·이동·페이지 넘김\n• 필압: 누르는 힘에 따라 선 굵기 변화\n• S펜 측면 버튼: 누르는 동안 임시 지우개\n• 펜 뒤쪽 지우개: 지원 기기에서 자동 인식\n\n일반 정전식 펜과 손가락은 필압을 지원하지 않습니다.").setPositiveButton("확인",null).show();}
    private void updateColorButton(){GradientDrawable d=new GradientDrawable();d.setShape(GradientDrawable.OVAL);d.setColor(selectedColor|0xFF000000);d.setStroke(dp(3),Color.WHITE);colorButton.setBackground(d);colorButton.setColorFilter(Color.WHITE);}
    private void chooseColor(){String[] names={"선샤인","민트","로즈","스카이","라벤더"};int[] colors={0x66FFDE59,0x6654C27A,0x66FF6B9A,0x66549CF5,0x66B67CF2};LinearLayout panel=new LinearLayout(this);panel.setOrientation(LinearLayout.VERTICAL);panel.setPadding(dp(22),dp(6),dp(22),dp(18));TextView guide=new TextView(this);guide.setText("PDF 위에 표시할 색상을 선택하세요");guide.setTextColor(0xFF64748B);guide.setTextSize(14);guide.setPadding(0,0,0,dp(18));panel.addView(guide);LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER);panel.addView(row,new LinearLayout.LayoutParams(-1,-2));AlertDialog dialog=new AlertDialog.Builder(this).setTitle("하이라이트 색상").setView(panel).setNegativeButton("취소",null).create();for(int i=0;i<colors.length;i++){final int c=colors[i];ImageButton s=new ImageButton(this);s.setContentDescription(names[i]);GradientDrawable bg=new GradientDrawable();bg.setShape(GradientDrawable.OVAL);bg.setColor(c|0xFF000000);bg.setStroke(dp(c==selectedColor?4:1),c==selectedColor?NAVY:0xFFE2E8F0);s.setBackground(bg);s.setOnClickListener(v->{selectedColor=c;pageView.setHighlightMode(highlightMode,selectedColor);updateColorButton();dialog.dismiss();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(46),dp(46),1);p.setMargins(dp(4),0,dp(4),0);row.addView(s,p);}dialog.show();}
    private void toggleBookmark(){if(renderer==null)return;if(!store.bookmarks.add(currentPage))store.bookmarks.remove(currentPage);store.save();updateBookmarkButton();}
    private void updateBookmarkButton(){boolean marked=renderer!=null&&store.bookmarks.contains(currentPage);bookmarkButton.setImageResource(marked?R.drawable.ic_star:R.drawable.ic_star_outline);bookmarkButton.setColorFilter(marked?0xFFF59E0B:NAVY);bookmarkButton.setContentDescription(marked?"즐겨찾기 해제":"즐겨찾기 추가");}
    private void toggleFullscreen(){fullscreen=!fullscreen;header.setVisibility(fullscreen?View.GONE:View.VISIBLE);tabStrip.setVisibility(fullscreen?View.GONE:View.VISIBLE);bottomBar.setVisibility(fullscreen?View.GONE:View.VISIBLE);fullscreenExit.setVisibility(fullscreen?View.VISIBLE:View.GONE);if(Build.VERSION.SDK_INT>=30){WindowInsetsController c=getWindow().getInsetsController();if(c!=null){c.setSystemBarsBehavior(WindowInsetsController.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE);if(fullscreen)c.hide(WindowInsets.Type.systemBars());else c.show(WindowInsets.Type.systemBars());}}else getWindow().getDecorView().setSystemUiVisibility(fullscreen?View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY|View.SYSTEM_UI_FLAG_FULLSCREEN|View.SYSTEM_UI_FLAG_HIDE_NAVIGATION:View.SYSTEM_UI_FLAG_VISIBLE);root.requestApplyInsets();}
    @Override public void onBackPressed(){if(fullscreen)toggleFullscreen();else super.onBackPressed();}
    @Override public void onHighlightCreated(AnnotationStore.Mark mark){store.marks.add(mark);store.save();pageView.invalidate();}
    @Override public void onMemoPointRequested(int page,float x,float y){EditText input=new EditText(this);input.setHint("메모를 입력하세요");input.setPadding(dp(24),dp(12),dp(24),dp(12));new AlertDialog.Builder(this).setTitle("새 메모").setView(input).setPositiveButton("저장",(d,w)->{String note=input.getText().toString().trim();if(note.isEmpty())return;AnnotationStore.Mark m=new AnnotationStore.Mark();m.page=page;m.left=Math.max(0f,x-0.025f);m.right=Math.min(1f,x+0.025f);m.top=Math.max(0f,y-0.025f);m.bottom=Math.min(1f,y+0.025f);m.color=selectedColor;m.note=note;m.noteOnly=true;store.marks.add(m);store.save();pageView.invalidate();toast("파란 메모 표시를 탭하면 수정하거나 삭제할 수 있습니다");}).setNegativeButton("취소",null).show();}
    @Override public void onMarkTapped(AnnotationStore.Mark mark){editMark(mark);}
    @Override public void onZoomGestureStarted(){if(highlightMode||memoMode||outlineMode){highlightMode=memoMode=outlineMode=false;pageView.setHighlightMode(false,selectedColor);pageView.setMemoMode(false);pageView.setOutlineMode(false);updateToolStates();}}
    @Override public void onPageSwipe(int direction){showPage(currentPage+direction);}
    @Override public void onOutlinePointRequested(int page,float x,float y){EditText input=new EditText(this);input.setHint("예: 2. 세부 검토사항");input.setPadding(dp(24),dp(12),dp(24),dp(12));new AlertDialog.Builder(this).setTitle("개요 제목").setView(input).setPositiveButton("저장",(d,w)->{String title=input.getText().toString().trim();if(title.isEmpty())title="페이지 "+(page+1);AnnotationStore.OutlineItem item=new AnnotationStore.OutlineItem();item.page=page;item.x=x;item.y=y;item.title=title;store.outlines.add(item);store.save();outlineMode=false;pageView.setOutlineMode(false);toast("개요에 저장했습니다");}).setNegativeButton("취소",null).show();}
    @Override public void onInkChanged(){if(store!=null){store.save();if(activeSession!=null)activeSession.redoStrokes.clear();}}
    private void editMark(AnnotationStore.Mark mark){EditText input=new EditText(this);input.setHint("메모를 입력하세요");input.setText(mark.note);input.setPadding(dp(24),dp(12),dp(24),dp(12));AlertDialog dialog=new AlertDialog.Builder(this).setTitle("페이지 "+(mark.page+1)+(mark.noteOnly?" 메모":" 하이라이트")).setIcon(R.drawable.ic_delete).setView(input).setPositiveButton("저장",(d,w)->{mark.note=input.getText().toString().trim();store.save();pageView.invalidate();}).setNegativeButton(mark.noteOnly?"메모 삭제":"하이라이트 삭제",(d,w)->{store.marks.remove(mark);store.save();pageView.invalidate();toast(mark.noteOnly?"메모를 삭제했습니다":"하이라이트를 삭제했습니다");}).setNeutralButton("취소",null).create();dialog.setOnShowListener(d->dialog.getButton(AlertDialog.BUTTON_NEGATIVE).setTextColor(0xFFD32F2F));dialog.show();}
    private void showTools(){String[] t={"전체 화면","S펜 필기도구","페이지 썸네일", "개요 지점 추가","개요 목록","페이지 넘김 방향 · "+(verticalPageSwipe?"수직":"수평"),"메모·하이라이트 목록","즐겨찾기 목록","페이지로 이동","주석 백업(JSON)","사용법"};new AlertDialog.Builder(this).setTitle("도구").setItems(t,(d,w)->{if(w==0)toggleFullscreen();else if(w==1)showInkTools();else if(w==2)toggleSidebar();else if(w==3)toggleOutlineMode();else if(w==4)showOutlineList();else if(w==5)choosePageSwipeDirection();else if(w==6)showMarkList();else if(w==7)showBookmarks();else if(w==8)goToPage();else if(w==9)exportAnnotations();else showHelp();}).show();}
    private void showOutlineList(){if(store==null||store.outlines.isEmpty()){if(renderer==null)toast("PDF를 먼저 여세요");else new AlertDialog.Builder(this).setTitle("개요").setMessage("저장된 개요가 없습니다.\n\n‘개요 지점 추가’를 누른 뒤 PDF의 원하는 위치를 탭하세요.").setPositiveButton("지점 추가",(d,w)->toggleOutlineMode()).setNegativeButton("닫기",null).show();return;}List<AnnotationStore.OutlineItem> items=new ArrayList<>(store.outlines);String[] labels=new String[items.size()];for(int i=0;i<items.size();i++)labels[i]=(i+1)+". "+items.get(i).title+"  ·  p."+(items.get(i).page+1);new AlertDialog.Builder(this).setTitle("개요").setItems(labels,(d,i)->showOutlineItem(items.get(i))).setPositiveButton("지점 추가",(d,w)->toggleOutlineMode()).setNegativeButton("닫기",null).show();}
    private void showOutlineItem(AnnotationStore.OutlineItem item){new AlertDialog.Builder(this).setTitle(item.title).setMessage("페이지 "+(item.page+1)).setPositiveButton("이동",(d,w)->{showPage(item.page);pageView.post(()->pageView.focusOnPoint(item.x,item.y));}).setNegativeButton("삭제",(d,w)->{store.outlines.remove(item);store.save();toast("개요 항목을 삭제했습니다");}).setNeutralButton("취소",null).show();}
    private void choosePageSwipeDirection(){String[] choices={"수평 · 좌우로 넘기기","수직 · 위아래로 넘기기"};new AlertDialog.Builder(this).setTitle("페이지 넘김 방향").setSingleChoiceItems(choices,verticalPageSwipe?1:0,(dialog,which)->{verticalPageSwipe=which==1;pageView.setVerticalPageSwipe(verticalPageSwipe);recentPrefs.edit().putBoolean("vertical_page_swipe",verticalPageSwipe).apply();dialog.dismiss();toast(verticalPageSwipe?"위로 밀면 다음 페이지로 이동합니다":"왼쪽으로 밀면 다음 페이지로 이동합니다");}).setNegativeButton("취소",null).show();}
    private void showMarkList(){List<AnnotationStore.Mark> items=new ArrayList<>(store.marks);if(items.isEmpty()){toast("저장된 하이라이트나 메모가 없습니다");return;}String[] labels=new String[items.size()];for(int i=0;i<items.size();i++){String note=items.get(i).note;labels[i]="p."+(items.get(i).page+1)+"  "+(note==null||note.isEmpty()?"(메모 없음)":note);}new AlertDialog.Builder(this).setTitle("메모·하이라이트").setItems(labels,(d,i)->{showPage(items.get(i).page);editMark(items.get(i));}).show();}
    private void showBookmarks(){if(store.bookmarks.isEmpty()){toast("즐겨찾기한 페이지가 없습니다");return;}List<Integer> pages=new ArrayList<>(store.bookmarks);Collections.sort(pages);String[] labels=new String[pages.size()];for(int i=0;i<pages.size();i++)labels[i]="페이지 "+(pages.get(i)+1);new AlertDialog.Builder(this).setTitle("즐겨찾기").setItems(labels,(d,i)->showPage(pages.get(i))).show();}
    private void goToPage(){if(renderer==null)return;EditText input=new EditText(this);input.setInputType(2);input.setHint("1 ~ "+renderer.getPageCount());new AlertDialog.Builder(this).setTitle("페이지로 이동").setView(input).setPositiveButton("이동",(d,w)->{try{showPage(Integer.parseInt(input.getText().toString())-1);}catch(Exception ignored){toast("올바른 페이지를 입력하세요");}}).setNegativeButton("취소",null).show();}
    private void exportAnnotations(){if(documentUri==null)return;Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,documentTitle.replaceAll("(?i)\\.pdf$","")+"_annotations.json");startActivityForResult(i,EXPORT_JSON);}
    private void showHelp(){new AlertDialog.Builder(this).setTitle("PDF Note 사용법").setMessage("• PDF 추가: 상단 폴더 또는 탭의 + 버튼\n• 문서 전환·닫기: 상단 문서 탭과 × 버튼\n• S펜 필기: 아래쪽 펜 아이콘\n• 페이지 썸네일: 상단 페이지 목록 아이콘\n• 개요 저장: 메뉴의 ‘개요 지점 추가’ 후 원하는 위치 탭\n• 페이지 넘김: PDF를 좌우 또는 위아래로 밀기\n• 하이라이트: 버튼을 누르고 문장을 좌우로 드래그\n• 메모: 메모 아이콘을 누른 뒤 원하는 위치를 탭\n• 확대: 두 손가락으로 핀치\n• 확대 화면 이동: 한 손가락으로 상하좌우 드래그\n• 전체 화면: 위쪽 확장 아이콘\n• 즐겨찾기: 별 아이콘\n\n필기·개요·하이라이트·메모·즐겨찾기는 문서별로 저장되며 원본 PDF는 변경하지 않습니다.").setPositiveButton("확인",null).show();}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
    private void closeAllDocuments(){for(DocumentSession s:new ArrayList<>(sessions)){if(s.renderer!=null)s.renderer.close();if(s.descriptor!=null)try{s.descriptor.close();}catch(IOException ignored){}}sessions.clear();renderer=null;descriptor=null;}
    @Override protected void onDestroy(){closeAllDocuments();super.onDestroy();}
}
